INSERT INTO input VALUES(2,'aesthetic, esthetic','aj');
INSERT INTO input VALUES(3,'aesthetically, esthetically','av');
INSERT INTO input VALUES(4,'aesthetics, esthetics','n');
INSERT INTO input VALUES(6,'allistic','n');
INSERT INTO input VALUES(7,'allistic','aj');
INSERT INTO input VALUES(8,'Anthea','n');
INSERT INTO input VALUES(9,'artisanal','aj');
INSERT INTO input VALUES(12,'auditable','aj');
INSERT INTO input VALUES(13,'autocorrect','n');
INSERT INTO input VALUES(14,'autocorrect','v');
INSERT INTO input VALUES(15,'automation','n');
INSERT INTO input VALUES(16,'biblically','av');
INSERT INTO input VALUES(17,'BioNTech','n');
INSERT INTO input VALUES(18,'biopharmaceutical','n');
INSERT INTO input VALUES(19,'biopharmaceutical','aj');
INSERT INTO input VALUES(20,'blacksmithing','n');
INSERT INTO input VALUES(21,'blogosphere','n');
INSERT INTO input VALUES(22,'bromance','n');
INSERT INTO input VALUES(23,'bugfix, bug-fix','n');
INSERT INTO input VALUES(24,'bugfix, bug-fix','aj');
INSERT INTO input VALUES(26,'centric','aj');
INSERT INTO input VALUES(27,'Chainlink','n');
INSERT INTO input VALUES(28,'characterization, characterisation','n');
INSERT INTO input VALUES(30,'chip seal, chipseal','n');
INSERT INTO input VALUES(31,'cleantech, clean-tech','n');
INSERT INTO input VALUES(32,'CLI','n');
INSERT INTO input VALUES(33,'clickstream','n');
INSERT INTO input VALUES(36,'codebase, code base','n');
INSERT INTO input VALUES(37,'Coinbase','n');
INSERT INTO input VALUES(38,'commenter','n');
INSERT INTO input VALUES(40,'containerisation','n');
INSERT INTO input VALUES(41,'containerization','n');
INSERT INTO input VALUES(42,'cosplayer','n');
INSERT INTO input VALUES(43,'coworking, co-working','n');
INSERT INTO input VALUES(44,'coworking, co-working','aj');
INSERT INTO input VALUES(45,'Crohn''s','n');
INSERT INTO input VALUES(46,'crowdsource','v');
INSERT INTO input VALUES(47,'crowdsourcing','n');
INSERT INTO input VALUES(49,'cytometry','n');
INSERT INTO input VALUES(50,'dApp, dapp','n');
INSERT INTO input VALUES(51,'decomposer','n');
INSERT INTO input VALUES(52,'deduplicate, de-duplicate','v');
INSERT INTO input VALUES(53,'deduplication, de-duplication','n');
INSERT INTO input VALUES(54,'demonym','n');
INSERT INTO input VALUES(55,'deplatform','v');
INSERT INTO input VALUES(56,'deserialization, deserialisation','n');
INSERT INTO input VALUES(57,'deserialize, deserialise','v');
INSERT INTO input VALUES(58,'desulfurization','n');
INSERT INTO input VALUES(60,'duplicative','aj');
INSERT INTO input VALUES(63,'dysregulation','n');
INSERT INTO input VALUES(65,'Egyptologist','n');
INSERT INTO input VALUES(66,'Egyptology','n');
INSERT INTO input VALUES(67,'electrochemical','aj');
INSERT INTO input VALUES(68,'empanada','n');
INSERT INTO input VALUES(69,'ENS','n');
INSERT INTO input VALUES(70,'epicycle','n');
INSERT INTO input VALUES(71,'esthetician, aesthetician','n');
INSERT INTO input VALUES(72,'ETH','n');
INSERT INTO input VALUES(73,'Ethereum','n');
INSERT INTO input VALUES(74,'ethicist','n');
INSERT INTO input VALUES(76,'expectedly','av');
INSERT INTO input VALUES(77,'fandom','n');
INSERT INTO input VALUES(78,'gameplay, game play','n');
INSERT INTO input VALUES(80,'grayscale, greyscale','n');
INSERT INTO input VALUES(81,'grayscale, greyscale','aj');
INSERT INTO input VALUES(82,'hard fork, hardfork','n');
INSERT INTO input VALUES(83,'hemorrhagic, haemorrhagic','aj');
INSERT INTO input VALUES(84,'homeschool, home school','n');
INSERT INTO input VALUES(85,'homeschool, home-school, home school','v');
INSERT INTO input VALUES(86,'homeschooler, home-schooler, home schooler','n');
INSERT INTO input VALUES(88,'hyperbolize, hyperbolise','v');
INSERT INTO input VALUES(92,'ideation','n');
INSERT INTO input VALUES(93,'impactful','aj');
INSERT INTO input VALUES(95,'Instagram','n');
INSERT INTO input VALUES(96,'Instagram','v');
INSERT INTO input VALUES(97,'in vivo','aj');
INSERT INTO input VALUES(98,'in vivo','av');
INSERT INTO input VALUES(99,'IPFS','n');
INSERT INTO input VALUES(101,'liftgate','n');
INSERT INTO input VALUES(104,'livestream, live stream, live-stream','n');
INSERT INTO input VALUES(105,'livestream, live stream, live-stream','v');
INSERT INTO input VALUES(106,'LLM','n');
INSERT INTO input VALUES(107,'lowball','n');
INSERT INTO input VALUES(108,'lowball','v');
INSERT INTO input VALUES(110,'mainnet','n');
INSERT INTO input VALUES(111,'mansplainer','n');
INSERT INTO input VALUES(112,'MetaMask','n');
INSERT INTO input VALUES(113,'microblog','n');
INSERT INTO input VALUES(114,'microblog','v');
INSERT INTO input VALUES(116,'millimeter','n');
INSERT INTO input VALUES(117,'misclick, mis-click','n');
INSERT INTO input VALUES(118,'misclick, mis-click','v');
INSERT INTO input VALUES(119,'Moderna','n');
INSERT INTO input VALUES(120,'multitask','v');
INSERT INTO input VALUES(123,'neurodivergent','aj');
INSERT INTO input VALUES(124,'neurodiverse','aj');
INSERT INTO input VALUES(125,'neurodiversity','n');
INSERT INTO input VALUES(126,'neurotypical','n');
INSERT INTO input VALUES(127,'neurotypical','aj');
INSERT INTO input VALUES(128,'nitride','n');
INSERT INTO input VALUES(129,'nitride','v');
INSERT INTO input VALUES(131,'non-refoulement, nonrefoulement','n');
INSERT INTO input VALUES(133,'off-chain, offchain','aj');
INSERT INTO input VALUES(134,'off-screen, offscreen','aj');
INSERT INTO input VALUES(135,'off-screen, off screen, offscreen','av');
INSERT INTO input VALUES(136,'on-chain, onchain','aj');
INSERT INTO input VALUES(137,'OpenSea','n');
INSERT INTO input VALUES(138,'parklet','n');
INSERT INTO input VALUES(139,'personalization, personalisation','n');
INSERT INTO input VALUES(142,'podcaster','n');
INSERT INTO input VALUES(143,'prosecutable','aj');
INSERT INTO input VALUES(144,'psilocybin','n');
INSERT INTO input VALUES(145,'ramen','n');
INSERT INTO input VALUES(146,'Rebecca, Rebekah','n');
INSERT INTO input VALUES(147,'refoulement','n');
INSERT INTO input VALUES(148,'reinitialize, reinitialise','v');
INSERT INTO input VALUES(149,'reportable','aj');
INSERT INTO input VALUES(150,'responder','n');
INSERT INTO input VALUES(152,'rewritable, rewriteable','aj');
INSERT INTO input VALUES(153,'rheumatologist','n');
INSERT INTO input VALUES(154,'rheumatology','n');
INSERT INTO input VALUES(155,'sanitization, sanitisation','n');
INSERT INTO input VALUES(156,'scalable','aj');
INSERT INTO input VALUES(158,'solvability','n');
INSERT INTO input VALUES(159,'splitter','n');
INSERT INTO input VALUES(160,'stand-up, standup','n');
INSERT INTO input VALUES(161,'stand-up, standup','aj');
INSERT INTO input VALUES(162,'staycation, stay-cation','n');
INSERT INTO input VALUES(163,'stim','n');
INSERT INTO input VALUES(164,'stim','v');
INSERT INTO input VALUES(165,'stimming','n');
INSERT INTO input VALUES(167,'surveil','v');
INSERT INTO input VALUES(168,'tastemaker','n');
INSERT INTO input VALUES(169,'testnet','n');
INSERT INTO input VALUES(170,'TikTok','n');
INSERT INTO input VALUES(171,'TikTok','v');
INSERT INTO input VALUES(172,'tokamak, tokomak','n');
INSERT INTO input VALUES(173,'tokenization, tokenisation','n');
INSERT INTO input VALUES(174,'tokenize, tokenise','v');
INSERT INTO input VALUES(175,'toroid','n');
INSERT INTO input VALUES(176,'toroidal','aj');
INSERT INTO input VALUES(178,'tradable','aj');
INSERT INTO input VALUES(179,'transactional','aj');
INSERT INTO input VALUES(181,'transformative','aj');
INSERT INTO input VALUES(185,'unintuitive','aj');
INSERT INTO input VALUES(186,'Uniswap','n');
INSERT INTO input VALUES(188,'unsynchronized, unsynchronised','aj');
INSERT INTO input VALUES(191,'videoconference, video conference, video-conference','n');
INSERT INTO input VALUES(192,'vlog','n');
INSERT INTO input VALUES(193,'vlog','v');
INSERT INTO input VALUES(194,'vlogger','n');
INSERT INTO input VALUES(195,'voxel','n');
INSERT INTO input VALUES(196,'wheatgrass','n');
INSERT INTO input VALUES(197,'wordlist, word list','n');
INSERT INTO input VALUES(198,'workspace, work space','n');
INSERT INTO input VALUES(199,'writable, writeable','aj');
INSERT INTO input VALUES(200,'YouTube','n');
INSERT INTO input VALUES(201,'YouTube','v');
INSERT INTO input VALUES(203,'inductor','n');
INSERT INTO input VALUES(204,'subtractive','aj');
INSERT INTO input VALUES(205,'tunable','aj');
INSERT INTO input VALUES(206,'verifier','n');
INSERT INTO input VALUES(208,'homolog','n');
INSERT INTO input VALUES(209,'hypermetropia','n');
INSERT INTO input VALUES(210,'liquidus','n');
INSERT INTO input VALUES(211,'luteinizing hormone','n');
INSERT INTO input VALUES(212,'microswitch','n');
INSERT INTO input VALUES(213,'plasmolyze','v');
INSERT INTO input VALUES(214,'plasmolysis','n');
INSERT INTO input VALUES(215,'trabecula','n');
INSERT INTO input VALUES(216,'transaxle','n');
INSERT INTO input VALUES(217,'uninterruptible','aj');
INSERT INTO input VALUES(218,'unminable','aj');
INSERT INTO input VALUES(220,'Comirnaty','n');
INSERT INTO input VALUES(221,'Covifenz','n');
INSERT INTO input VALUES(222,'Jcovden','n');
INSERT INTO input VALUES(223,'Nuvaxovid','n');
INSERT INTO input VALUES(224,'QazVac','n');
INSERT INTO input VALUES(225,'Spikevax','n');
INSERT INTO input VALUES(226,'Vaxzevria','n');
INSERT INTO input VALUES(228,'AstraZeneca','n');
INSERT INTO input VALUES(229,'CanSino','n');
INSERT INTO input VALUES(230,'Janssen','n');
INSERT INTO input VALUES(231,'Novavax','n');
INSERT INTO input VALUES(232,'Pfizer','n');
INSERT INTO input VALUES(233,'Sinopharm','n');
INSERT INTO input VALUES(234,'Sinovac','n');
INSERT INTO input VALUES(235,'Medicago','n');
INSERT INTO input VALUES(236,'Valneva','n');
INSERT INTO input VALUES(238,'cytometer','n');
INSERT INTO input VALUES(240,'revictimisation, revictimization','n');
INSERT INTO input VALUES(242,'Egyptological','aj');
INSERT INTO input VALUES(244,'AuDHD','abbr');
INSERT INTO input VALUES(246,'ADHD','abbr');
INSERT INTO input VALUES(247,'allism','n');
INSERT INTO input VALUES(248,'dyscalculia','n');
INSERT INTO input VALUES(249,'dyspraxia','n');
INSERT INTO input VALUES(250,'hyposensitive','aj');
INSERT INTO input VALUES(251,'hyposensitivity','n');
INSERT INTO input VALUES(252,'neurodevelopment','n');
INSERT INTO input VALUES(253,'neurodevelopmental','aj');
INSERT INTO input VALUES(255,'list server, listserver','n');
INSERT INTO input VALUES(257,'emoji','n');
INSERT INTO input VALUES(258,'LOL, lol','abbr');
INSERT INTO input VALUES(259,'Wi-Fi, WiFi, wi-fi, wifi','n');
INSERT INTO input VALUES(261,'fan fiction, fan-fiction, fanfiction','n');
INSERT INTO input VALUES(262,'fan fic, fan-fic, fanfic','n');
INSERT INTO input VALUES(264,'mansplain','v');
INSERT INTO input VALUES(265,'non-binary, nonbinary','aj');
INSERT INTO input VALUES(266,'pansexual','aj');
INSERT INTO input VALUES(267,'pansexual','n');
INSERT INTO input VALUES(269,'microplastic','n');
INSERT INTO input VALUES(270,'microplastic','aj');
INSERT INTO input VALUES(272,'influencer','n');
INSERT INTO input VALUES(273,'Instagrammer','n');
INSERT INTO input VALUES(274,'macro-influencer, macroinfluencer','n');
INSERT INTO input VALUES(275,'mega-influencer, megainfluencer','n');
INSERT INTO input VALUES(276,'micro-influencer, microinfluencer','n');
INSERT INTO input VALUES(277,'nano-influencer, nanoinfluencer','n');
INSERT INTO input VALUES(278,'TikToker','n');
INSERT INTO input VALUES(279,'YouTuber','n');
INSERT INTO input VALUES(281,'DeFi','n');
INSERT INTO input VALUES(282,'NFT','n');
INSERT INTO input VALUES(283,'stablecoin','n');
INSERT INTO input VALUES(284,'Web3','n');
INSERT INTO input VALUES(286,'AUD','abbr');
INSERT INTO input VALUES(287,'CAD','abbr');
INSERT INTO input VALUES(288,'CHF','abbr');
INSERT INTO input VALUES(289,'CNY','abbr');
INSERT INTO input VALUES(290,'EUR','abbr');
INSERT INTO input VALUES(291,'GBP','abbr');
INSERT INTO input VALUES(292,'JPY','abbr');
INSERT INTO input VALUES(293,'USD','abbr');
INSERT INTO input VALUES(294,'DKK','abbr');
INSERT INTO input VALUES(295,'NOK','abbr');
INSERT INTO input VALUES(296,'NZD','abbr');
INSERT INTO input VALUES(297,'SEK','abbr');
INSERT INTO input VALUES(299,'TUI','n');
INSERT INTO input VALUES(301,'hatchling','n');
INSERT INTO input VALUES(302,'pollen','n');
INSERT INTO input VALUES(303,'redshift','n');
INSERT INTO input VALUES(304,'redshift','v');
INSERT INTO input VALUES(305,'blueshift','n');
INSERT INTO input VALUES(306,'blueshift','v');
INSERT INTO input VALUES(307,'archosaur','n');
INSERT INTO input VALUES(308,'Archosauria','n');
INSERT INTO input VALUES(309,'conodont','n');
INSERT INTO input VALUES(310,'crocodilian','aj');
INSERT INTO input VALUES(311,'crocodilian','n');
INSERT INTO input VALUES(312,'endothermy','n');
INSERT INTO input VALUES(313,'microfossil','n');
INSERT INTO input VALUES(314,'mudstone','n');
INSERT INTO input VALUES(315,'nonavian','aj');
INSERT INTO input VALUES(316,'nonavian','n');
INSERT INTO input VALUES(317,'osculum','n');
INSERT INTO input VALUES(318,'palynomorph','n');
INSERT INTO input VALUES(319,'proteobacterium','n');
INSERT INTO input VALUES(320,'pterosaur','n');
INSERT INTO input VALUES(321,'tholin','n');
INSERT INTO input VALUES(322,'bloodedness','n');
INSERT INTO input VALUES(323,'glomeration','n');
INSERT INTO input VALUES(324,'protovertebra','n');
INSERT INTO input VALUES(325,'electropneumatic','aj');
INSERT INTO input VALUES(326,'macOS','n');
INSERT INTO input VALUES(327,'equipotential','aj');
INSERT INTO input VALUES(328,'colorization, colourisation, colourization','n');
INSERT INTO input VALUES(329,'HGV','abbr');
INSERT INTO input VALUES(330,'HMI','abbr');
INSERT INTO input VALUES(331,'integumentary','aj');
INSERT INTO input VALUES(332,'magnetomotive','aj');
INSERT INTO input VALUES(333,'mechatronics','n');
INSERT INTO input VALUES(334,'melanism','n');
INSERT INTO input VALUES(335,'metalloid','n');
INSERT INTO input VALUES(336,'microcontroller','n');
INSERT INTO input VALUES(337,'microstructure','n');
INSERT INTO input VALUES(338,'multivibrator','n');
INSERT INTO input VALUES(339,'optocoupler','n');
INSERT INTO input VALUES(340,'phasor','n');
INSERT INTO input VALUES(341,'pre-program, preprogram','v');
INSERT INTO input VALUES(342,'ratiometer','n');
INSERT INTO input VALUES(343,'reactance','n');
INSERT INTO input VALUES(344,'WordPad','n');
INSERT INTO input VALUES(374,'malware','n');
INSERT INTO input VALUES(376,'biofuel','n');
INSERT INTO input VALUES(377,'freeware','n');
INSERT INTO input VALUES(378,'HVAC','abbr');
INSERT INTO input VALUES(379,'hydropower','n');
INSERT INTO input VALUES(380,'index','n');
INSERT INTO input VALUES(381,'intranet','n');
INSERT INTO input VALUES(382,'reinstallation','n');
INSERT INTO input VALUES(383,'vertex','n');
INSERT INTO input VALUES(384,'abiotic','aj');
INSERT INTO input VALUES(385,'astable','aj');
INSERT INTO input VALUES(386,'bioenergetics','n');
INSERT INTO input VALUES(387,'biogeography','n');
INSERT INTO input VALUES(388,'biomagnification','n');
INSERT INTO input VALUES(389,'breakerless','aj');
INSERT INTO input VALUES(390,'co-evolution, coevolution','n');
INSERT INTO input VALUES(391,'contactor','n');
INSERT INTO input VALUES(392,'decalcify','v');
INSERT INTO input VALUES(393,'demultiplexer','n');
INSERT INTO input VALUES(394,'desolder','v');
INSERT INTO input VALUES(395,'distributorless','aj');
INSERT INTO input VALUES(396,'dynamometer','n');
INSERT INTO input VALUES(397,'electrochemistry','n');
INSERT INTO input VALUES(398,'electropneumatics','n');
INSERT INTO input VALUES(399,'equipotential','n');
INSERT INTO input VALUES(401,'mitzvoth','n');
INSERT INTO input VALUES(403,'co-evolve, coevolve','v');
INSERT INTO input VALUES(405,'glyph','n');
INSERT INTO input VALUES(407,'backtrace','n');
INSERT INTO input VALUES(408,'backtrace','v');
INSERT INTO input VALUES(410,'bohrium','n');
INSERT INTO input VALUES(411,'copernicium','n');
INSERT INTO input VALUES(412,'darmstadtium','n');
INSERT INTO input VALUES(413,'dubnium','n');
INSERT INTO input VALUES(414,'flerovium','n');
INSERT INTO input VALUES(415,'hassium','n');
INSERT INTO input VALUES(416,'livermorium','n');
INSERT INTO input VALUES(417,'meitnerium','n');
INSERT INTO input VALUES(418,'moscovium','n');
INSERT INTO input VALUES(419,'nihonium','n');
INSERT INTO input VALUES(420,'oganesson','n');
INSERT INTO input VALUES(421,'roentgenium','n');
INSERT INTO input VALUES(422,'seaborgium','n');
INSERT INTO input VALUES(423,'tennessine','n');
INSERT INTO input VALUES(425,'CMOS','n');
INSERT INTO input VALUES(427,'Karen','n');
INSERT INTO input VALUES(428,'Caryn','n');
INSERT INTO input VALUES(430,'ecossais, écossais','n');
INSERT INTO input VALUES(431,'ecurie, écurie','n');
INSERT INTO input VALUES(432,'Ecosse, Écosse','n');
INSERT INTO input VALUES(434,'unhewn','aj');
INSERT INTO input VALUES(436,'parameterisation, parameterization','n');
INSERT INTO input VALUES(438,'chip seal, chip-seal, chipseal','aj');
INSERT INTO input VALUES(439,'chip seal, chipseal','v');
INSERT INTO input VALUES(441,'folksonomy','n');
INSERT INTO input VALUES(443,'DeFi','abbr');
INSERT INTO input VALUES(444,'ETH','abbr');
INSERT INTO input VALUES(446,'ENS','abbr');
INSERT INTO input VALUES(447,'IPFS','abbr');
INSERT INTO input VALUES(449,'de-dupe, dedupe','v');
INSERT INTO input VALUES(450,'de-dupe, dedupe','n');
INSERT INTO input VALUES(452,'stupa','n');
INSERT INTO input VALUES(453,'sysadmin','n');
INSERT INTO input VALUES(454,'triage','n');
INSERT INTO input VALUES(455,'triage','v');
INSERT INTO input VALUES(456,'geodata','n');
INSERT INTO input VALUES(457,'mergeable','aj');
INSERT INTO input VALUES(459,'deferable, deferrable','aj');
INSERT INTO input VALUES(460,'repurpose','v');
INSERT INTO input VALUES(462,'Ashkenazi, Ashkenazic','aj');
INSERT INTO input VALUES(463,'Ashkenazi','n');
INSERT INTO input VALUES(465,'doomer','n');
INSERT INTO input VALUES(466,'doomerism','n');
